name: Docker Release
on:
  push:
    branches:
      - main

env:
  REGISTRY_HOSTNAME: ghcr.io
  TAG: latest

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Environment Variables
        run: |
          export BUILD_IMAGE=${{ env.REGISTRY_HOSTNAME }}/${{ github.repository }}:${{ env.TAG }}
          echo "BUILD_IMAGE=$BUILD_IMAGE"
          echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_ENV

      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache Node Modules
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Cleanup Node Modules
        run: yarn install --production --ignore-scripts --prefer-offline

      - name: Build Docker Image
        run: docker build -t $BUILD_IMAGE .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY_HOSTNAME }} -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker push $BUILD_IMAGE
