name: Docker Release
on:
  push:
    branches:
      - main

env:
  IMAGE_ID: ghcr.io/${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build amd64 Docker Image
        run: docker build --platform linux/amd64 --push -t ${{ env.IMAGE_ID }}:latest .
