name: Cloud Run Deploy
on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Deploy to Cloud Run
        uses: dmsi-io/gha-cloudrun-deploy@v1
        id: deploy
        with:
          GCP_IDENTITY_PROVIDER: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Pull Request Comments
        uses: dmsi-io/gha-pull-request@v1.2
        with:
          GHA_ACCESS_TOKEN: ${{ secrets.GHA_ACCESS_TOKEN }}
          url: ${{ steps.deploy.outputs.url }}
