name: Build Application on PR
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 'feature/docker-caching'

env:
  IMAGE_ID: ghcr.io/${{ github.repository }}

jobs:
  lint-build-docker:
    name: Lint, Build and Dockerize NextJS App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache Node Modules
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Cleanup Node Modules
        run: yarn install --production --ignore-scripts --prefer-offline

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_ID }}:${{ github.sha }} .
