name: Build Application on PR
on:
  pull_request:
    branches:
      - main

env:
  IMAGE_ID: ghcr.io/${{ github.repository }}

jobs:
  lint-build:
    # skip this step for now
    if: github.ref_type == 'tag'
    name: Lint and Build NextJS App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache Node Modules
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

  docker:
    name: Dockerize NextJS App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Set up Docker with Caching
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build amd64 Docker Image
        run: docker build -t ${{ env.IMAGE_ID }}:${{ github.sha }} .
